import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed); 
        double rnd = generator.nextDouble();




		boolean boy = false;
		boolean girl = false;
		int sum = 0;//children in each family
	    int sum2 = 0;
	    int sum3 = 0;
	    int sum4 = 0;
	    double a = 0;
	    int allChildren = 0;//all the children
	    String common = "wrong";

		for (int i =0 ; i< T ; i++)
		{

		 while (boy == false || girl == false )
	 	 {
	 	    a = (int)( 2 * generator.nextDouble()) ;
	 	    	 	 	 	      System.out.println("1");

	 	 	if (a == 0)
	 	 	 {
	 	 	 	boy = true;

	 	 	 }
	 	 	 else
	 	 	 {
	 	 	 	girl = true;
	 	 	 }
	 	 	 sum +=1;

	 	 	 allChildren ++;

	 	 }

	 	 if (sum>= 4)
	 	 	sum4 ++;
	 	 else
	 	 {
	 	 	if(sum == 2)
	 	 		sum2 ++;
	 	 	else
	 	 		sum3++;
	 	 }


			 boy = false;
			 girl = false;
			 sum = 0;

	    }

	    
	    if ((sum4>sum2)&&(sum4>sum3))
	    		common = "4 or more";
	    else
	    {
	    	if (((sum3>sum2)&&(sum3>sum4)) || ((sum3>sum2)&& (sum3==sum4)) )
	    		common = "3";
	    	else
	    	{
	    	     common = "2";
	       }
	    }

		System.out.println(allChildren);
		System.out.println(allChildren/T);



		// double average = allChildren/T;
		System.out.println("Average: " + (double) allChildren / T + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + sum2);
		System.out.println("Number of families with 3 children: " + sum3);
		System.out.println("Number of families with 4 or more children: " + sum4);
		System.out.println("The most common number of children is " + common + ".");


		
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
		    
	}
}
